Dev
ntqogly/PlaylistMaker pull request #1
Opened 2024-07-25 23:07 UTC by ntqogly

2024-07-26 17:55 UTC, DmitrijEgorow commented
Экран не соответствует дизайну: нет заголовка, неправильные отступы между элементами и от краев устройства, сильно мелкий текст
![Screenshot_20240727_002457](https://github.com/user-attachments/assets/6500565a-ddf3-44cd-8519-14c3077ed95f)

2024-07-26 17:57 UTC, DmitrijEgorow commented
Экран не соответствует дизайну: используется два оттенка белого, неправильные отступы у элементов и их взаимное расположение, цвет текста
![Screenshot_20240727_002539](https://github.com/user-attachments/assets/89c9da78-aa59-4ed3-86ea-599498231bfd)

2024-07-26 18:00 UTC, DmitrijEgorow requested changes

2024-07-26 18:00 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_main.xml
> +            app:cornerRadius="20dp"
Нужно вынести в dimens

2024-07-26 18:00 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_settings.xml
> +            android:id="@+id/rl_share"
Иной стиль именования идентификатора, стоит унифицировать

2024-07-26 18:00 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_settings.xml
> +            android:id="@+id/rl_termsOfUse"
Не надо мешать camelCase и _

2024-07-26 18:00 UTC, DmitrijEgorow commented on app/src/main/res/values/strings.xml
> +    <string name="shareTextView">Поделиться приложением</string>
Зачем дважды?

2024-07-27 15:52 UTC, DmitrijEgorow commented
> Экран не соответствует дизайну: нет заголовка, неправильные отступы между элементами и от краев устройства, сильно мелкий текст ![Screenshot_20240727_002457](https://private-user-images.githubusercontent.com/36837067/352621532-6500565a-ddf3-44cd-8519-14c3077ed95f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU3OTksIm5iZiI6MTcyMjA5NTQ5OSwicGF0aCI6Ii8zNjgzNzA2Ny8zNTI2MjE1MzItNjUwMDU2NWEtZGRmMy00NGNkLTg1MTktMTRjMzA3N2VkOTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMmY0NTkxYzZjZWExN2FjM2ZkOGQ0MjVjYzNmZjNkMmQ3ZjM3YTkxZGNmMWRiNmQ1ZTY2NDg2NmVkYjMyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YQuSsT6xOK5_2u1Oo957wk6suDIhqleB4fQ_zW4G1Sg)

Актуально: неправильные отступы между элементами и от краев устройства

2024-07-27 15:53 UTC, DmitrijEgorow commented
> Экран не соответствует дизайну: используется два оттенка белого, неправильные отступы у элементов и их взаимное расположение, цвет текста ![Screenshot_20240727_002539](https://private-user-images.githubusercontent.com/36837067/352621611-89c9da78-aa59-4ed3-86ea-599498231bfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTU3OTksIm5iZiI6MTcyMjA5NTQ5OSwicGF0aCI6Ii8zNjgzNzA2Ny8zNTI2MjE2MTEtODljOWRhNzgtYWE1OS00ZWQzLTg2ZWEtNTk5NDk4MjMxYmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMjEyOTQ3NmVkYjAwM2U0NzRjNGI2NDAxMWY2ZjdkODk5ZDU1MTAyNDQ4ZTQ2MjdkNTBjYTMwNmYxOTNlNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N1051fkhWMDCxTbR9pJlaxRFBRtAPW6XdxkABJm2vSM)

Актуально: неправильные отступы у элементов и их взаимное расположение

2024-07-27 17:49 UTC, ntqogly commented
Все еще понимаю в чем проблема с макетом. Переделал заново, вроде выглядит так же.

2024-07-28 18:15 UTC, merged